language: java
sudo: false

script:
    - bash -c 'cd gradle; ./gradlew build'
    - bash -c 'cd maven; mvn --fail-at-end package'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/02c1585dc4e3b6297974
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
